---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: attendees-repo
  - name: version

outputs:
  - name: build-output

run:
  path: attendees-repo/ci/tasks/build.sh
  args: [
    --input-dir, attendees-repo,
    --output-dir, build-output,
    --version-file, version/number,
    --artifactId, attendees,
    --packaging, jar
  ]
